#site settings
name: Lottie Clarke
#title: 
description: ""
#baseurl: "" 
#url: "" 
#tagline: 

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
permalink: /blog/:year/:month/:day/:title
paginate: 4
paginate_path: '/blog/page:num/'

