#Site settings
name: Lottie Clarke
title: Lottie Clarke 
description: "Lottie Clarke: fiction and non-fiction writer."
#baseurl: "" 
#url: "" 
#tagline: 
twitter_username: astronomnomy
tumblr_username: astronomnomy
remote_theme: mmistakes/so-simple-theme


# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
permalink: /blog/:year/:month/:day/:title
paginate: 4
paginate_path: '/blog/page:num/'
excerpt_separator: "<!--more-->"

